#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "immich"
name = "Immich"
description.en = "Photo and video backup solution directly from your mobile phone"
description.fr = "Sauvegarde de photos et de vidéos directement depuis votre mobile"

version = "1.123.0~ynh1"

maintainers = ["loowiz"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://immich.app"
admindoc = "https://github.com/immich-app/immich#getting-started"
userdoc = "https://github.com/immich-app/immich#getting-started"
code = "https://github.com/immich-app/immich"

[integration]
yunohost = ">= 12"
helpers_version = "2.1"
architectures = ["arm64", "amd64"]
multi_instance = false

ldap = false
sso = false

disk = "2G" # Likely needs updating
ram.build = "2G" # Likely needs updating
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.ports]
    main.default = 2283
    machinelearning.default = 3003

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt.extras.docker]
    repo = "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/debian __YNH_DEBIAN_VERSION__ stable"
    key = "https://download.docker.com/linux/debian/gpg"
    packages = [
        "docker-ce",
        "docker-ce-cli",
        "containerd.io",
        "docker-buildx-plugin",
        "docker-compose-plugin"
    ]
