#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# MODIFY URL IN FAIL2BAN CONF
#=================================================

ynh_config_remove_fail2ban
domain_regex=${domain//[.]/\\.}
failregex="^<HOST>.*\"(POST).*(401).*($domain_regex).*$"
ynh_config_add_fail2ban --logpath="/var/log/nginx/$domain-access.log" --failregex=$failregex
ynh_systemctl --service="fail2ban" --action="restart"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Immich Server is listening" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
