#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --source_id="main" --dest_dir="$install_dir/"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

mkdir "$install_dir/db" # Used for database path in env file
ynh_config_add --template="env" --destination="$install_dir/.env"
ynh_config_add --template="docker-compose.yml" --destination="$install_dir/docker-compose.yml"


#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-server" --template="$app.service"
ynh_config_add_systemd --service="$app-machine-learning" --template="$app.service"
# machine learning service is the same as the server service but is just there for saving/reading logs (might be a better way of doing this)

yunohost service add "$app-server" --description="Immich Server" --log="/var/log/$app/$app-server.log"
yunohost service add "$app-machine-learning" --description="Immich Machine Learning" --log="/var/log/$app/$app-machine-learning.log"

ynh_multimedia_build_main_dir
ynh_multimedia_addaccess "$app"

ynh_config_add_logrotate

ynh_config_add_fail2ban --logpath="/var/log/$app/$app-server.log" --failregex="$app-server.*Failed login attempt for user.+from ip address\s?<ADDR>"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-server" --action="start" --wait_until="Immich Server is listening" --log_path="/var/log/$app/$app.log" --timeout=900
ynh_systemctl --service="$app-machine-learning" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
