#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

db_password=$(ynh_string_random)
ynh_config_add --template="env" --destination="$install_dir/.env"
ynh_config_add --template="docker-compose.yml" --destination="$install_dir/docker-compose.yml"


#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-server" --template="$app.service"

yunohost service add "$app-server" --description="Immich Server"

ynh_multimedia_build_main_dir
ynh_multimedia_addaccess "$app"

ynh_config_add_fail2ban --logpath="/var/log/nginx/access.log" --failregex="^.*"(POST).*" (401) .*($domain_regex).*$"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-server" --action="start" --wait_until="Immich Server is listening" --log_path="systemd" --timeout=900

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
