#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# RESTORE THE DATABASE
#=================================================
ynh_script_progression "Restoring the database..."

myynh_restore_db

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app-server.service"
ynh_restore "/etc/systemd/system/$app-machine-learning.service"

ynh_config_add_systemd --service="$app-server" --template="$app.service"
ynh_config_add_systemd --service="$app-machine-learning" --template="$app.service"
# machine learning service is the same as the server service but is just there for saving/reading logs (might be a better way of doing this)

yunohost service add "$app-server" --description="Immich Server" --log="/var/log/$app/$app-server.log"
yunohost service add "$app-machine-learning" --description="Immich Machine Learning" --log="/var/log/$app/$app-machine-learning.log"

ynh_multimedia_build_main_dir
ynh_multimedia_addaccess "$app"

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/etc/fail2ban/jail.d/$app.conf"
ynh_restore "/etc/fail2ban/filter.d/$app.conf"
ynh_systemctl --service="fail2ban" --action="restart"

#=================================================
# RESTORE THE DATABASE
#=================================================

myynh_restore_db

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app-server" --action="start" --wait_until="Immich Server is listening" --log_path="/var/log/$app/$app.log" --timeout=900
ynh_systemctl --service="$app-machine-learning" --action="start" --log_path="/var/log/$app/$app.log"

ynh_systemctl --service="nginx" --action="reload"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
