#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if ynh_app_upgrading_from_version_before 1.118.2~ynh1
then
    if ynh_hide_warnings yunohost service status "$app-microservices" >/dev/null
    then
        yunohost service remove "$app-microservices"
    fi
    ynh_config_remove_systemd "$app-microservices"
    find "/var/log/$app/" -name "$app-microservices.log*" -delete
    ynh_app_setting_delete --key="port_microservices"
    ynh_app_setting_delete --key="checksum__var_www_immich_env-machine-learning"
    ynh_app_setting_delete --key="checksum__var_www_immich_env-server"
    ynh_app_setting_delete --key="checksum__etc_systemd_system_immich-microservices.service"
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-server" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_safe_rm "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="env" --destination="$install_dir/.env"
ynh_config_add --template="docker-compose.yml" --destination="$install_dir/docker-compose.yml"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app" --template="$app.service"

yunohost service add "$app-server" --description="Immich Server"

ynh_multimedia_build_main_dir
ynh_multimedia_addaccess "$app"

ynh_config_add_fail2ban --logpath="/var/log/nginx/access.log" --failregex="^.*\"(POST).*\" (401) .*($domain_regex).*$"

#=================================================
# UPDATE IMMICH FROM DOCKER
#=================================================
ynh_script_progression "Updating $app from Docker..."

myynh_docker_pull

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Immich Server is listening" --log_path="systemd" --timeout=900

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
